# Generated by Django 3.0.5 on 2020-04-24 18:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hof', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='time',
            field=models.TimeField(default=datetime.time(8, 0)),
        ),
    ]
