# Generated by Django 3.0.5 on 2020-05-01 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hof', '0005_dotw_TextChoices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='day_of_the_week',
            field=models.CharField(choices=[('Monday', 'Mon'), ('Tuesday', 'Tue'), ('Wednesday', 'Wed'), ('Thursday', 'Thu'), ('Friday', 'Fri')], max_length=12),
        ),
        migrations.AlterField(
            model_name='score',
            name='date',
            field=models.DateTimeField(verbose_name='Due date'),
        ),
    ]
