# Generated by Django 3.0.5 on 2020-05-06 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hof', '0006_dotw_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='acquired_blood_cells',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='task',
            name='max_blood_cells',
            field=models.FloatField(default=1),
        ),
    ]
