# Generated by Django 3.0.5 on 2020-05-23 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hof', '0007_auto_20200506_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='acquired_blood_cells',
            field=models.FloatField(default=1),
        ),
    ]
